pluginManagement {
  repositories {
    gradlePluginPortal()
    mavenCentral()
  }
}

dependencyResolutionManagement {
  versionCatalogs {
    libs {
      from(files("libs.versions.toml"))
    }
  }
  repositories {
    mavenCentral()
  }
}

rootProject.name = 'spice'
include ':model'
include ':core'
