load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")
load("//tools:junit5.bzl", "kt_jvm_test")

kt_jvm_test(
    name = "BreadthFirstDependencyVisitorTest",
    srcs = ["BreadthFirstDependencyVisitorTest.kt"],
    friends = ["//model"],
    test_class = "com.squareup.spice.model.traversal.BreadthFirstDependencyVisitorTest",
    deps = [
        "//model:test",
        "@maven//:com_google_truth_truth",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
    ],
)
