name: CI

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:

jobs:
  bazel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: bazelbuild/setup-bazelisk@v3

      - name: Build
        run: bazel build //...

      - name: Test
        run: bazel test //... --test_output=errors
